### ISSUE TITLE
Upgrade node to latest LTS

### ISSUE THREAD

**Issue by jzbrooks** [travelperk/label-requires-reviews-action#574]
Node 12 has been out of support for some time and there are some security concerns in my org for using a tool on an old runtime that isn't seeing security patches.

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by jzbrooks** [comment]
Hopefully this is as simple as updating the runtime in the action file, but I created this for discussion in case there are known issues around doing so.

**Comment by namelivia** [comment]
👋 Thanks for the heads-up, it should be fairly simple, I'll take a look later today!
